//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecom.Model
{
    using System;
    
    public enum OrderStatusType : int
    {
        pending_payment = 1,
        payment_recieved = 2,
        pending_fulfillment = 3,
        cancelled = 4,
        completed = 5
    }
}
